### ISSUE TITLE
.gitignore specifies invalid bower directory

### ISSUE THREAD

**Issue by jarrodldavis** [lukelarsen/generator-node-express#1]
I'm not sure if there is something I am doing wrong, but on a clean generation, the `.gitignore` ignores the directory `app/bower_components`, but `.bowerrc` specifies `assets/bower_components`. Was this intended behavior?

**Comment by lukelarsen** [comment]
Hey jarrodldavis,

Wow this was a while ago. Sorry I never responded. I will see if I can find some time to go look. I'll have to get familiar with this project again since it has been sooooooo long. Thanks
